apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: spring-boot-docker-deployment
spec:
  selector:
    matchLabels:
      app: spring-boot-docker
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: spring-boot-docker
    spec:
      containers:
        - name: spring-boot-docker
          image: sandydevops8/spring-boot-docker # Image that will be used to containers in the cluster GITHUB
          #image: 810426675067.dkr.ecr.us-east-1.amazonaws.com/springboot-eks:latest #ECR sandydevops8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster
            
---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: spring-boot-docker-service
spec:
  selector:
    app: spring-boot-docker
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service. on local Kubernetes machine for testing
  #type: LoadBalancer #deploying in AWS